# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13lZlMXiBYCeN59gAMRf_mUpCq4eyMhux
"""

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0FICMfKDqbAAFlBUUTPHE6Et_SYU3wO
"""

import numpy as np
import matplotlib.pyplot as plt
s=np.linspace(-10,10,20) # range of values over which functions are definned 
Mx=np.exp(-(s**2)/2) # moment generating function or spectrum of f(n1)
My=np.exp(-(s**2)/2) # moment generating function or spectrum of f(n2)
Mz=Mx*My # moment generating function or spectrum of f(z)
n=20
c,bin_es=np.histogram(Mz,bins=n,normed=True)
cdf=np.cumsum(c) # cumulative sum or cdf 
#figure,axes=plt.subplots(nrows=2,ncols=2)

# plots of all defined functions
plt.figure()
plt.plot(s,Mx)
plt.xlabel('S-->')
plt.ylabel('Mn1(S)')
plt.title('spectrum of f(n1)')

plt.figure()
plt.plot(s,My)
plt.xlabel('S-->')
plt.ylabel('Mn2(S)')
plt.title('spectrum of f(n2)')

plt.figure()
plt.plot(s,Mz)
plt.xlabel('S-->')
plt.ylabel('simulation plot of Mz(S)')
plt.title('spectrum of f(z)')

plt.figure()
plt.plot(bin_es[1:],cdf/cdf[-1])
plt.title('empirical cdf of Mz(s)')

plt.show()