# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1plJdf8y4eHzQXIBIjBx9bUfbVR2EeLAr
"""

import numpy as np
import matplotlib.pyplot as plt
x=np.linspace(0,2,3) #number of tails
print(x)
pt=1/4               #probability of tail 
ph=3/4               #probability of head
p=[]

#probability distribution of number of tails is obtained as below

for i in range(0,3):
     if i==0: 
        print(i)
        p.append(ph*ph)
     elif i==1:
        print(i)
        p.append(ph*pt)
     else:
        p.append(pt*pt)
print(p)
plt.stem(x,p)
plt.xlabel('X-->')
plt.ylabel('P(X)-->')
plt.title('Pmf of X')
plt.show()