# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfXcpWJUYWwV9JrvpGHVB8B1tcbjq-Rv
"""

import numpy as np
import matplotlib.pyplot as plt
l=np.linspace(0,1000,1000) #1000 samples of inputs generation
ph=3/4; #probability of head
pt=1/4; #probability of tail
k=1000; # maximum possible number of tails in 1000 tosses
pr=[];
for i in range(0,1000):
     pr.append((ph**k)*(pt**i)); #expression for probability
     k=k-1;
plt.stem(l,pr,'r')
plt.xlabel('number of Tails(X) ')
plt.ylabel('probability of X ')
plt.show()