# -*- coding: utf-8 -*-
"""Copy of Copy of Rvsp2_Binom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FqyLjLumNj_YE_VHkD3zjldDv8MG7k82
"""

############################### RVSP Assignment-2 @ EE21RESCH01008 ################################ 


from scipy.stats import binom 
import matplotlib.pyplot as plt

############Generatting probabilities using Binomial Distribution########## 
n1 = 2;#####10 tosses
n2=1000;#########1000 tosses
p = 0.25
#####simulation for 2 tosses
K1 = list(range(n1 + 1)) ######all posible number of  tails 
Prob1 = [binom.pmf(r, n1, p) for r in K1 ] ###binomial Distribution
print(Prob1)
plt.figure()
plt.stem(K1,Prob1,'r')
plt.xlabel('NUMBER OF TAILS(X)')
plt.ylabel('P(X)')
plt.title('simulation for 2 tosses')
#####simulation for 1000 tosses
K2 = list(range(n2 + 1)) ######all posible number of  tails 
Prob2 = [binom.pmf(r, n2, p) for r in K2 ] ###binomial Distribution

plt.figure()
plt.stem(K2,Prob2,'k')
plt.xlabel('NUMBER OF TAILS(X)')
plt.ylabel('P(X)')
plt.title('simulation for 1000 tosses')

plt.show()