# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dOVCj_o-Pq-69RBlqrP-D6rwK3kgsjJz
"""

########## Assignment-RVSP-3 ####################
### Name:Anuradha U
### ID:EE21RESCH01008
### Problem:Prob_2.8

import numpy as np
from scipy.stats import bernoulli

Trials=1000000 ######### Number of Repetitions of the event

##### Probabilities Given

Prg1=0.6       ######### winning probability of Group1
Prg2=0.4       ######### winning probability of Group2
Prng1= 0.7     ######### Probability that G1 launches new product
Prng2 = 0.3    ######### Probability that G2 launches new product

###### Successes and Failures for a Group winning out of given number of Trials

Sg1= bernoulli.rvs(size= Trials, p = Prg1) 
Sg2= bernoulli.rvs(size= Trials, p = Prg2)

###### Success and Failures that a Group Launches new product

Sng1= bernoulli.rvs(size= Trials, p = Prng1)
Sng2= bernoulli.rvs(size= Trials, p = Prng2)

######## Counting Number of successes  for all possible events

Pg1 = np.size(np.nonzero(Sg1 == 1))
Pg2 = np.size(np.nonzero(Sg2 == 1))
Png1 = np.size(np.nonzero(Sng1 == 1))
Png2 = np.size(np.nonzero(Sng2 == 1))

######## Applying  Bayes Theorem to find prob that product being introduced by Group2 
prob= (Png2*Pg2)/(Png2*Pg2+Png1*Pg1)

print("probability that the new product was introduced by Group2:", prob)