# -*- coding: utf-8 -*-
"""rvsp_ass_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWSX7ZKlCyXmkPod8jAsq_Kob8YDEzc0
"""

from scipy.stats import binom 
import matplotlib.pyplot as plt
import numpy as np


###### 10 balls in an urn


n=4;
p = 9/10 ## probability that the ball drawn is marked with non-zero digit
K1 = list(range(n + 1)) 
## binomial
Prob1 = [binom.pmf(r, n, p) for r in K1 ]
print(Prob1)

## cdf
c=0;
cdf=[];
for i in range(len(Prob1)):
     c+=Prob1[i];
     cdf=np.append(cdf,c);
print(c)
print(cdf)


#### PMF ####
plt.figure()
plt.subplot(1,2,1)
plt.stem(K1,Prob1)
plt.xlabel('Number of balls marked non-zero(X)')
plt.ylabel(' P(X)')
plt.title('PMF of 10 balls in urn')

plt.subplot(1,2,2)
plt.plot(K1,cdf)
plt.title('CDF')
###### 1000 balls in an urn

n1=1000;
p1=999/1000;
K11=list(range(n1+1));
Prob11=[binom.pmf(r,n1,p1) for r in K11]

### cdf
c1=0;
cdf2=[];
for i in range(len(Prob11)):
      c1+=Prob11[i]
      cdf2=np.append(cdf2,c1);
##### pmf

plt.figure()
plt.subplot(1,2,1)
plt.stem(K11,Prob11)
plt.xlabel('X')
plt.ylabel('P(X)')
plt.title('PMF for 1000 balls in an urn')

plt.subplot(1,2,2)
plt.plot(K11,cdf2)
plt.title('CDF')

#### cdf